site_name: Paraiba Hot Dog
site_description: Documentação do projeto Paraiba Hot Dog
site_url: https://mach1r0.github.io/Paraiba-Hot-Dog/
repo_url: https://github.com/mach1r0/Paraiba-Hot-Dog
repo_name: Paraiba-Hot-Dog

theme:
  name: material
  language: pt-BR

nav:
  - Inicio: index.md
  - Reunioes:
    - Reuniao 01: Reunioes/Reuniao-01.md
    - Reuniao 02: Reunioes/Reuniao-02.md
  - Ponto de Controle 01:
      - Product Backlog: Ponto de controle 01/Product-Backlog.md
