site_name: Paraiba Hot Dog
site_description: Documentação do projeto Paraiba Hot Dog
site_url: https://mach1r0.github.io/Paraiba-Hot-Dog/
repo_url: https://github.com/mach1r0/Paraiba-Hot-Dog
repo_name: Paraiba-Hot-Dog

theme:
  name: material
  logo: img/logo-black.jpeg
  language: pt-BR
  palette:
    - scheme: default
      primary: black
      accent: yellow

extra_css:
  - stylesheets/extra.css

nav:
  - Inicio: index.md
  - Ponto de Controle 01:
      - Reunioes: Ponto de controle 01/Reunioes.md
      - Product Backlog: Ponto de controle 01/Product-Backlog.md
