site_name: Paraíba Hot Dog
site_description: Documentação oficial do sistema Paraíba Hot Dog

theme:
  name: material
  logo: img/logo-black.jpeg
  language: pt-BR
  palette:
    - scheme: default
      primary: black
      accent: yellow
  features:
    - navigation.sections
    - navigation.expand
    - toc.integrate

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - md_in_html
  - tables
  - admonition

nav:
  - Início: index.md
  - Sobre o Projeto: sobre.md
  - Módulos: modulos.md
  - Arquitetura: arquitetura.md
  - Guia de Início: guia-inicio.md
  - Design e Diagramas:
      - Protótipos (Figma): design/prototipos.md
      - Diagramas: design/diagramas.md
  - Requisitos:
      - Backlog do Produto: requisitos/backlog.md
  - Desenvolvimento:
      - Frontend: desenvolvimento/frontend.md
      - Backend: desenvolvimento/backend.md
      - Documentação: desenvolvimento/documentacao.md
